version: '3.9'

services:
  lavalink:
    image: fredboat/lavalink:0206007
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgressql/data
      - ./ZenithBeepData/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    restart: on-failure
    ports:
      - "5432:5432"
  app:
    build: 
      context: .
      args:
        TOKEN: ${TOKEN}
        LOG: ${LOGS}
        NAME_DB: ${POSTGRES_DB}
        USER_DB: ${POSTGRES_USER}
        HOST_DB: ${POSTGRES_HOST}
        PORT_DB: ${POSTGRES_PORT}
        PASSWORD_DB: ${POSTGRES_PASSWORD} 
        LAVALINK_HOST: ${LAVALINK_HOST}
        LAVALINK_PASSWORD: ${LAVALINK_PASSWORD}    
    command: sh -c "./publish/build/ZenithBeep"  
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - lavalink

volumes:
  pgdata:
  lavalinkdata: