version: '3.9'

services:
  lavalink-v3:
    build:
      context: ./Lavalink-v3
    container_name: lavalink_v3
    restart: unless-stopped
    networks:
      - lavalink-net
    expose:
      - 2333


  app:
    build: 
      context: .
    container_name: ZenithBeepBot
    depends_on:
      - lavalink-v3
    restart: always
    networks:
      - lavalink-net


networks:
  lavalink-net:
    name: lavalink_net