version: '3.9'

services:
  lavalink:
    image: fredboat/lavalink:0206007
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgressql/data
    restart: on-failure
    ports:
      - "5432:5432"
  database-management:
    build:
      context: ./ZenithBeepData
      dockerfile: Dockerfile
    env_file:
      - .env
    command: sh -c "./migrate.sh"
    depends_on:
      - db
  bot:
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file: 
      - .env
    restart: always
    depends_on:
      - db
      - lavalink

volumes:
  pgdata:
  lavalinkdata:
