//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZenithBeep.ResourcesBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Help_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZenithBeep.ResourcesBot.Help-en", typeof(Help_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙ Others.
        /// </summary>
        public static string IntaractionModuleOthers {
            get {
                return ResourceManager.GetString("IntaractionModuleOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎟 Roles.
        /// </summary>
        public static string IntaractionModuleRoles {
            get {
                return ResourceManager.GetString("IntaractionModuleRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗝 Roomers.
        /// </summary>
        public static string IntaractionModuleRoomers {
            get {
                return ResourceManager.GetString("IntaractionModuleRoomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛠 Utility.
        /// </summary>
        public static string IntaractionModuleUtility {
            get {
                return ResourceManager.GetString("IntaractionModuleUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎵 Music.
        /// </summary>
        public static string InteractionModuleMusic {
            get {
                return ResourceManager.GetString("InteractionModuleMusic", resourceCulture);
            }
        }
    }
}
